version: '3.3'

services:
  db:
    image: mysql_compose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - docker_compose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  flask:
    depends_on:
      - db
    image: flask_compose
    ports:
      - "5000:5000"
    restart: always
    networks:
      - docker_compose

networks:
  docker_compose: